version: '3'
services:
  express-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
    env_file:
      - .env
